CREATE TABLE SALARIES(
ID NUMBER(*,0) primary key,
EMPLOYEE_ID NUMBER(*,0) NOT NULL,
PROJECT_ID NUMBER(*,0),
SALARY NUMBER(10,2) NOT NULL
);

CREATE TABLE PROJECTS(
ID NUMBER(*,0) primary key,
CODE VARCHAR2(255 BYTE) NOT NULL,
MANAGER_ID NUMBER(*,0),
BUDGET NUMBER(10,2) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE
);

CREATE TABLE EMPLOYEES(
ID NUMBER(*,0) primary key,
MANAGER_ID NUMBER(*,0),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2(255 BYTE) NOT NULL
);

ALTER TABLE SALARIES
ADD CONSTRAINT FK_SALARY_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES EMPLOYEES(ID);

ALTER TABLE SALARIES
ADD CONSTRAINT FK_SALARY_PROJECT
FOREIGN KEY (PROJECT_ID)
REFERENCES PROJECTS(ID);

ALTER TABLE SALARIES
ADD CONSTRAINT CHECK_SALARY_GREATER_THAN CHECK (SALARY > 1000);

ALTER TABLE PROJECTS
ADD CONSTRAINT FK_MANAGER_PROJECT
FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES(ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_MANAGER
FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES(ID);


-- 1). Write a SQL query to fetch project code and count of employees (code, employees_count) sorted by employees_count in 
-- descending order. example 48205501099, 4

SELECT P.CODE, COUNT(S.EMPLOYEE_ID) AS EMPLOYEES_COUNT  
FROM PROJECTS P INNER JOIN SALARIES S 
ON P.ID = S.PROJECT_ID
GROUP BY P.CODE
ORDER BY EMPLOYEES_COUNT DESC;


-- 2) Write a query to fetch employee names and their salaries records order by salary asc. Return employee details even if 
-- he/she is not assigned to any project
